/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {

    public String getGreeting() {
        String i = "1";
        return i;
    }


    public static void main(String[] args) {
        App i2c = new App();
        System.out.println(i2c.getGreeting());
    }
}
