/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import robot.I2C.Java;

package.robot;

public class App {



    public String getGreeting() {
        String i = "1";
        return i;
    }


    public static void main(String[] args) {
        I2C.i2cConfig();
    }
}
