/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {


    


    public static void main(String[] args) {
        I2C obj = new I2C();
        obj.i2cConfig();
        
    }
}
